
  /*******************************************************************
  * CodeGenerationService.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package com.mbass.codegenerator;

import com.backendless.Backendless;
import com.backendless.async.callback.AsyncCallback;


public class CodeGenerationService
{
    static final String BACKENDLESS_HOST = "https://api.backendless.com";
    static final String SERVICE_NAME = "CodeGenerationService";
    static final String SERVICE_VERSION_NAME = "1.0.0";
    static final String APP_VERSION = "v1";
    static final String APP_ID = "4C698B7C-14B4-333A-FF28-AEC7D1B0D200";
    static final String SECRET_KEY = "A9B868D1-6B60-2933-FF38-90C567054B00";

    private static CodeGenerationService ourInstance = new CodeGenerationService();

    private CodeGenerationService(  )
    {
    }

    public static CodeGenerationService getInstance()
    {
        return ourInstance;
    }

    public static void initApplication()
    {
        Backendless.setUrl( CodeGenerationService.BACKENDLESS_HOST );
        // if you invoke this sample inside of android application, you should use overloaded "initApp" with "context" argument
        Backendless.initApp( CodeGenerationService.APP_ID, CodeGenerationService.SECRET_KEY, CodeGenerationService.APP_VERSION );
    }


    
    public int getCode()
    {
        Object[] args = new Object[]{};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getCode", args, int.class );
    }
    
    public void getCodeAsync(AsyncCallback<Integer> callback)
    {
        Object[] args = new Object[]{};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getCode", args, Integer.class, callback);
    }
    
}
